import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import api from "../lib/api";

const currency = (value) => `₹${Number(value || 0).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;

export default function Analysis() {
  const [data, setData] = useState(null);
  const [selectedReport, setSelectedReport] = useState(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { api.get("/api/analysis").then((response) => setData(response.data)).catch(console.error).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="flex justify-center py-24"><div className="h-8 w-8 animate-spin rounded-full border-2 border-brand-500 border-t-transparent" /></div>;
  const current = data?.current_period || {};
  const previous = data?.previous_period || {};
  const maxValue = Math.max(...(data?.monthly_reports || []).flatMap((report) => [report.sales, report.expenses]), 1);
  const change = (value, oldValue) => oldValue ? `${Math.round(((value - oldValue) / oldValue) * 100)}%` : "New";
  const cards = [["Current sales", currency(current.sales), change(current.sales, previous.sales), "text-brand-600"], ["Current expenses", currency(current.expenses), change(current.expenses, previous.expenses), "text-danger"], ["Current profit", currency(current.profit), change(current.profit, previous.profit), current.profit >= 0 ? "text-success" : "text-danger"], ["Profit margin", `${data?.profit_margin || 0}%`, "This month", "text-accent-600"]];
  return <div className="animate-fade-in">
    <div className="page-heading"><div><p className="eyebrow">Business analysis</p><h1>Make the next move wisely.</h1><p>Compare this month with the previous one and spot what deserves attention.</p></div><div className="date-chip"><span>Current period</span><strong>{new Date().toLocaleDateString(undefined, { month: "long", year: "numeric" })}</strong></div></div>
    <div className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value, note, color]) => <div className="stat-panel surface-panel" key={label}><p className="stat-label">{label}</p><p className={`stat-value ${color}`}>{value}</p><p className="stat-note">{note} vs previous month</p></div>)}</div>
    <div className="mb-6 grid gap-5 lg:grid-cols-[1.45fr_0.85fr]"><section className="surface-panel p-5"><div className="section-title"><div><h2>Monthly performance</h2><span>Sales and expenses across the last six months</span></div><span>Sales / Expenses</span></div><div className="bar-chart">{data?.monthly_reports?.map((report) => <div className="flex h-full flex-1 flex-col justify-end" key={`${report.year}-${report.month}`}><div className="bar-group"><div className="bar" style={{ height: `${Math.max((report.sales / maxValue) * 100, 2)}%` }} title={`Sales ${currency(report.sales)}`} /><div className="bar expense" style={{ height: `${Math.max((report.expenses / maxValue) * 100, 2)}%` }} title={`Expenses ${currency(report.expenses)}`} /></div><p className="bar-label">{report.label}</p></div>)}</div><div className="mt-4 flex gap-4 text-xs text-surface-500"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-brand-400" />Sales</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-accent-400" />Expenses</span></div></section><section className={`pulse surface-panel ${data?.pulse?.tone || "neutral"}`}><p className="pulse-status text-brand-600">Business pulse · {data?.pulse?.status}</p><h2>{data?.pulse?.title}</h2><p>{data?.pulse?.message}</p><Link to="/dashboard" className="mt-5 inline-block text-xs font-bold text-brand-600 hover:underline">Review today's activity →</Link></section></div>
    <section className="surface-panel p-5"><div className="section-title"><div><h2>Monthly reports</h2><span>Select a month to inspect its totals</span></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data?.monthly_reports?.map((report) => <button type="button" onClick={() => setSelectedReport(report)} className="rounded-lg bg-surface-50 p-4 text-left transition hover:bg-brand-50" key={`${report.year}-${report.month}`}><p className="text-xs font-bold uppercase tracking-wider text-surface-400">{report.label} {report.year}</p><p className="mt-2 text-sm font-bold text-surface-800">Sales {currency(report.sales)}</p><p className="mt-1 text-xs text-surface-500">Expenses {currency(report.expenses)} · Profit {currency(report.profit)}</p></button>)}</div>{selectedReport && <div className="mt-4 rounded-lg border border-brand-100 bg-brand-50 p-4 text-sm text-surface-700"><strong>{selectedReport.label} {selectedReport.year}</strong> recorded {currency(selectedReport.sales)} in sales, {currency(selectedReport.expenses)} in expenses, and {currency(selectedReport.profit)} profit.</div>}</section>
  </div>;
}